name: Deploy Backend to Mika Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry

            - name: Install dependencies with Poetry
              run: poetry install

            - name: Run deploy script
              run: bash ./scripts/mika-deploy.sh
